package de.swt2bib.ui;

import java.util.Properties;

/**
 *
 * @author root
 */
public abstract class ElternPanel extends javax.swing.JPanel {

    public final PanelHandler panelHandler;

    /**
     * Creates new form ElternPanel
     * @param panelHandler Angabe Panelhandler
     */
    public ElternPanel(PanelHandler panelHandler) {
        this.panelHandler = panelHandler;
    }

    public abstract void update();

    public abstract void updateLanguage(Properties props);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
