package de.swt2bib.ui;

import de.swt2bib.info.Informationen;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author root
 */
public class UI extends javax.swing.JFrame {

    private boolean online;

    /**
     * Creates new form UI
     */
    public UI(List genreListe, List kategorieListe, PanelHandler panelHandler, boolean online) {
        this.genreListe = new ArrayList<String>();
        this.kategorieListe = new ArrayList<String>();
        initComponents();
        setLayout(new java.awt.BorderLayout());
        setVisible(true);
        this.panelHandler = panelHandler;
        this.online = online;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beendenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beendenMenuActionPerformed
        try {
            panelHandler.ausloggen();
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Speichern nicht möglich.", "Beenden", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_beendenMenuActionPerformed

    private void LoginLogoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginLogoutMenuActionPerformed
        panelHandler.panelUnsichtbar();
        add(panelHandler.getLoginPanel());
        panelHandler.getLoginPanel().setVisible(true);
    }//GEN-LAST:event_LoginLogoutMenuActionPerformed

    private void editAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountMenuActionPerformed
        panelHandler.panelUnsichtbar();
        add(panelHandler.getAccountBearbeitenPanel());
        panelHandler.getAccountBearbeitenPanel().setAccount(panelHandler.getAktuellerUser());
        panelHandler.getAccountBearbeitenPanel().setVisible(true);
    }//GEN-LAST:event_editAccountMenuActionPerformed

    private void accountsBearbeitenItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsBearbeitenItemActionPerformed
        panelHandler.panelUnsichtbar();
        panelHandler.getAccountsBearbeitenPanel().fillTable();
        add(panelHandler.getAccountsBearbeitenPanel());
        panelHandler.getAccountsBearbeitenPanel().setVisible(true);
    }//GEN-LAST:event_accountsBearbeitenItemActionPerformed

    private void historyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyMenuActionPerformed
        panelHandler.panelUnsichtbar();
        panelHandler.getHistoryPanel().fillTable();
        add(panelHandler.getHistoryPanel());
        panelHandler.getHistoryPanel().setVisible(true);
    }//GEN-LAST:event_historyMenuActionPerformed

    private void aktuelleAusleiheMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktuelleAusleiheMenuActionPerformed
        panelHandler.panelUnsichtbar();
        panelHandler.getAusleihenPanel().setAccount(panelHandler.getAktuellerUser());
        panelHandler.getAusleihenPanel().fillTable();
        add(panelHandler.getAusleihenPanel());
        panelHandler.getAusleihenPanel().setVisible(true);
    }//GEN-LAST:event_aktuelleAusleiheMenuActionPerformed

    private void optionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionMenuActionPerformed
        panelHandler.panelUnsichtbar();
        add(panelHandler.getOptionPanel());
        panelHandler.getOptionPanel().setVisible(true);
    }//GEN-LAST:event_optionMenuActionPerformed

    private void ausleihenBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausleihenBearbeitenActionPerformed
        panelHandler.panelUnsichtbar();
        panelHandler.getAusleihenBearbeitenPanel().fillTable();
        add(panelHandler.getAusleihenBearbeitenPanel());
        panelHandler.getAusleihenBearbeitenPanel().setVisible(true);
    }//GEN-LAST:event_ausleihenBearbeitenActionPerformed

    private void informationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationMenuActionPerformed
        info();
    }//GEN-LAST:event_informationMenuActionPerformed

    private void supportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportMenuActionPerformed
        entwicklung();
    }//GEN-LAST:event_supportMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoginLogoutMenu;
    private javax.swing.JMenu accountMenu;
    private javax.swing.JMenuItem accountsBearbeitenItem;
    private javax.swing.JMenu administrationMenu;
    private javax.swing.JMenuItem aktuelleAusleiheMenu;
    private javax.swing.JMenuItem ausleihenBearbeiten;
    private javax.swing.JMenuItem beendenMenu;
    private javax.swing.JMenuItem editAccountMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem historyMenu;
    private javax.swing.JMenuItem informationMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem optionMenu;
    private javax.swing.JMenuItem supportMenu;
    // End of variables declaration//GEN-END:variables
    // Variablen
    List genreListe;
    List kategorieListe;
    PanelHandler panelHandler;

    private void info() {
        JOptionPane.showMessageDialog(rootPane, new Informationen().printEntwickler(), "Entwicklerinfo", JOptionPane.INFORMATION_MESSAGE);
    }

    private void entwicklung() {
        JOptionPane.showMessageDialog(rootPane, new Informationen().printEntwicklung(""), "Entwicklung", JOptionPane.ERROR_MESSAGE);
    }

    void setMitarbeiterOnline() {
        System.out.println("enable admin");
        administrationMenu.setEnabled(true);

        panelHandler.loadAdminAccounts();
        panelHandler.loadAusleihen();
    }

    void setUserOnline() {
        System.out.println("enable user");
        editAccountMenu.setEnabled(true);
        historyMenu.setEnabled(true);
        aktuelleAusleiheMenu.setEnabled(true);

        panelHandler.loadUserHistory();
        panelHandler.loadUserAusleihe();
    }

    void setUserOffline() {
        editAccountMenu.setEnabled(false);
        historyMenu.setEnabled(false);
        aktuelleAusleiheMenu.setEnabled(false);
        administrationMenu.setEnabled(false);
    }
}
