package de.swt2bib.ui.panels;

import de.swt2bib.fachlogik.accountverwaltung.Account;
import de.swt2bib.ui.ElternPanel;
import de.swt2bib.ui.PanelHandler;

/**
 *
 * @author root
 */
public class AccountBearbeitenPanel extends ElternPanel {

    /**
     * Creates new form AccountBearbeiten
     */
    
    private Account account;
    private boolean neu;
            
    /**
     *
     * @param panelHandler
     */
    public AccountBearbeitenPanel(PanelHandler panelHandler) {
        super(panelHandler);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sucheFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheFieldActionPerformed
        panelHandler.panelUnsichtbar();
        panelHandler.getSuchePanel().setSearchTitel(sucheField.getText());
        panelHandler.getSuchePanel().setVisible(true);
    }//GEN-LAST:event_sucheFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!plzField.getText().matches("[0-9]{5}")){
            meldungText.setText("PLZ ist ungültig.");
            return;
        }
        if(passwortField.getText().equals(checkPasswortField.getText())){
            String hausnummer = hausnummerField.getText();
            String name = nameField.getText();
            int plz = Integer.parseInt(plzField.getText());
            String stadt = stadtField.getText();
            String strasse = strasseField.getText();
            String vorname = vornameField.getText();
            String passwort = passwortField.getText();
            boolean mitarbeiter = mitarbeiterCheckBox.isSelected();
            save(account.getUserid(),hausnummer, name, plz, stadt, strasse, vorname, passwort,mitarbeiter);
            meldungText.setText("Änderungen wurden übernommen.");
        }
        else{
            meldungText.setText("Passwort stimmt nicht überein.");
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checkPasswortField;
    private javax.swing.JLabel checkPasswortLable;
    private javax.swing.JTextField hausnummerField;
    private javax.swing.JLabel hausnummerLable;
    private javax.swing.JLabel meldungText;
    private javax.swing.JCheckBox mitarbeiterCheckBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField passwortField;
    private javax.swing.JLabel passwortLable;
    private javax.swing.JTextField plzField;
    private javax.swing.JLabel plzLable;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stadtField;
    private javax.swing.JLabel stadtLable;
    private javax.swing.JTextField strasseField;
    private javax.swing.JLabel strasseLable;
    private javax.swing.JTextField sucheField;
    private javax.swing.JTextField vornameField;
    private javax.swing.JLabel vornameLable;
    // End of variables declaration//GEN-END:variables

    public void setAccount(Account a) {
        neu = false;
        account =a;
        if(a==null)
            System.out.println("null");
        hausnummerField.setText(a.getHausnummer());
        nameField.setText(a.getNachname());
        plzField.setText(""+a.getPlz());
        stadtField.setText(a.getOrt());
        strasseField.setText(a.getStrasse());
        vornameField.setText(a.getVorname());
        mitarbeiterCheckBox.setSelected(a.isMitarbeiter());
    }
        
    public void save(int id,String hausnummer, String name, int plz, String ort, String strasse, String vorname,String  passwort, boolean mitarbeiter){
        if(!neu)
        panelHandler.saveAccountChange(account.getUserid(),hausnummer, name ,plz ,ort, strasse,vorname,passwort, mitarbeiter,account.getUsername());
        else
          panelHandler.saveAccount(account.getUserid(),hausnummer, name ,plz , strasse,ort,vorname,passwort, mitarbeiter,account.getUsername());  
    }
    
    public void bearbeitenMitarbeiter(){
        mitarbeiterCheckBox.setEnabled(true);
    }

    void setNewAccount(Account a) {
        neu = true;
        account =a;
        if(a==null)
            System.out.println("null");
        hausnummerField.setText(a.getHausnummer());
        nameField.setText(a.getNachname());
        plzField.setText(""+a.getPlz());
        stadtField.setText(a.getOrt());
        strasseField.setText(a.getStrasse());
        vornameField.setText(a.getVorname());
        mitarbeiterCheckBox.setSelected(a.isMitarbeiter());
    }
}
