/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.swt2bib.ui.panels;

import de.swt2bib.ui.ElternPanel;
import de.swt2bib.ui.PanelHandler;
import de.swt2bib.info.exceptions.ConnectionError;
import java.io.IOException;

/**
 *
 * @author root
 */
public class LoginPanel extends ElternPanel {

    private boolean online = false;

    /**
     * Creates new form Login
     */
    public LoginPanel(PanelHandler panelHandler) {
        super(panelHandler);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(!online){
            einloggen();
            
        }
        else{
            try {
                ausloggen();
            } catch (Exception e) {
                System.err.println(e);
                meldungText.setText("Speichern der Sitzung nicht möglich");
            }
        }
            
    }//GEN-LAST:event_loginButtonActionPerformed

    private void sucheFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheFieldActionPerformed
        panelHandler.panelUnsichtbar();
        panelHandler.getSuchePanel().setSearchTitel(sucheField.getText());
        panelHandler.getSuchePanel().setVisible(true);
    }//GEN-LAST:event_sucheFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel meldungText;
    private javax.swing.JTextField passwortField;
    private javax.swing.JTextField sucheField;
    // End of variables declaration//GEN-END:variables

    private void einloggen(){
        String accountname = accountnameField.getText();
        String passwort = passwortField.getText();
        if(panelHandler.login(accountname, passwort)){
            meldungText.setText("Erfolgreich eingeloggt.");
            accountnameField.setEnabled(false);
            passwortField.setEnabled(false);
            loginButton.setText("Logout");
            online = true;
            panelHandler.panelUnsichtbar();
            panelHandler.getSuchePanel().setVisible(true);
        }else{
            meldungText.setText("Accountname oder Passwort falsch.");
        }
    }
    
    private void ausloggen() throws IOException, ConnectionError{
        panelHandler.ausloggen();
        meldungText.setText("Erfolgreich ausgeloggt.");
        loginButton.setText("Login");
        accountnameField.setEnabled(true);
        passwortField.setEnabled(true);
        online = false;
    }

}
