package de.swt2bib.fachlogik.languageverwaltung;

/**
 *
 * @author root
 */
public class PropertyName {

    //Allgemein
    public static final String SUCHEFIELD = "SUCHEFIELD";

    //AccountBearbeitenPanel
    public static final String ACCOUNTBEARBEITENPANEL_VORNAMELABLE = "ACCOUNTBEARBEITENPANEL_VORNAMELABLE";
    public static final String ACCOUNTBEARBEITENPANEL_STRASSELABLE = "ACCOUNTBEARBEITENPANEL_STRASSELABLE";
    public static final String ACCOUNTBEARBEITENPANEL_PLZLABLE = "ACCOUNTBEARBEITENPANEL_PLZLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_PASSWORTLABLE = "ACCOUNTBEARBEITENPANEL_PASSWORTLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_CHECKPASSWORTLABLE = "ACCOUNTBEARBEITENPANEL_CHECKPASSWORTLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_NAMELABLE = "ACCOUNTBEARBEITENPANEL_NAMELABLE";
    public static final String ACCOUNTBEARBEITENPANEL_HAUSNUMMERLABLE = "ACCOUNTBEARBEITENPANEL_HAUSNUMMERLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_STADTLABLE = "ACCOUNTBEARBEITENPANEL_STADTLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_MITARBEITERCHECKBOX = "ACCOUNTBEARBEITENPANEL_MITARBEITERCHECKBOX";
    public static final String ACCOUNTBEARBEITENPANEL_SAVEBUTTON = "ACCOUNTBEARBEITENPANEL_SAVEBUTTON";
    public static final String ACCOUNTBEARBEITENPANEL_MELDUNGTEXT = "meldungText";
    public static final String ACCOUNTBEARBEITENPANEL_PLZ = "ACCOUNTBEARBEITENPANEL_PLZ";
    public static final String ACCOUNTBEARBEITENPANEL_AENDERUNG = "ACCOUNTBEARBEITENPANEL_AENDERUNG";
    public static final String ACCOUNTBEARBEITENPANEL_PASSWORT = "ACCOUNTBEARBEITENPANEL_PASSWORT";

    //AccountsBearbeitenPanel
    public static final String ACCOUNTSBEARBEITENPANEL_SUCHEACCOUNTFIELD = "ACCOUNTSBEARBEITENPANEL_SUCHEACCOUNTFIELD";
    public static final String ACCOUNTSBEARBEITENPANEL_ANLEGENBUTTON = "ACCOUNTSBEARBEITENPANEL_ANLEGENBUTTON";
    public static final String ACCOUNTSBEARBEITENPANEL_BEARBEITENBUTTON = "ACCOUNTSBEARBEITENPANEL_BEARBEITENBUTTON";

    //AusleihenBearbeitenPanel
    public static final String AUSLEIHENBEARBEITENPANEL_ENTFERNENBUTTON = "AUSLEIHENBEARBEITENPANEL_ENTFERNENBUTTON";

    //AusleihenPanel
    public static final String AUSLEIHENPANEL_ENTFERNENBUTTON = "AUSLEIHENPANEL_ENTFERNENBUTTON";

    //HistoryPanel
    public static final String HISTORYPANEL_HISTORYSUCHEFIELD = "HISTORYPANEL_HISTORYSUCHEFIELD";
    public static final String HISTORYPANEL_KATEGORIELABLE = "HISTORYPANEL_KATEGORIELABLE";
    public static final String HISTORYPANEL_AUSWAEHLENBUTTON = "HISTORYPANEL_AUSWAEHLENBUTTON";

    //LoginPanel
    public static final String LOGINPANEL_MELDUNG = "LOGINPANEL_MELDUNG";
    public static final String LOGINPANEL_SUCCESSLOGIN = "LOGINPANEL_SUCCESSLOGIN";
    public static final String LOGINPANEL_SUCCESSLOGOUT = "LOGINPANEL_SUCCESSLOGOUT";
    public static final String LOGINPANEL_WRONG = "LOGINPANEL_WRONG";
    public static final String LOGINPANEL_FAILED = "LOGINPANEL_FAILED";
    public static final String LOGINPANEL_ACCOUNTLABEL = "LOGINPANEL_ACCOUNTLABEL";
    public static final String LOGINPANEL_ACCOUNTNAMEFIELD = "LOGINPANEL_ACCOUNTNAMEFIELD";
    public static final String LOGINPANEL_PASSWORDLABEL = "LOGINPANEL_PASSWORDLABEL";
    public static final String LOGINPANEL_PASSWORTFIELD = "LOGINPANEL_PASSWORTFIELD";
    public static final String LOGINPANEL_LOGINBUTTON = "LOGINPANEL_LOGINBUTTON";
    public static final String LOGINPANEL_LOGOUTBUTTON = "LOGINPANEL_LOGOUTBUTTON";

    //OptionPanel
    public static final String OPTIONPANEL_OPTIONLABEL = "OPTIONPANEL_OPTIONLABEL";
    public static final String OPTIONPANEL_UEBERNEHMENBUTTON = "OPTIONPANEL_UEBERNEHMENBUTTON";

    //SelectPanel
    public static final String SELECTPANEL_NAMELABLE = "SELECTPANEL_NAMELABLE";
    public static final String SELECTPANEL_STATUSLABLE = "SELECTPANEL_STATUSLABLE";
    public static final String SELECTPANEL_BESCHREIBUNGLABLE = "SELECTPANEL_BESCHREIBUNGLABLE";
    public static final String SELECTPANEL_KATEGORIELABLE = "SELECTPANEL_KATEGORIELABLE";
    public static final String SELECTPANEL_GENRELABLE = "SELECTPANEL_GENRELABLE";
    public static final String SELECTPANEL_AUSLEIHENBUTTON = "SELECTPANEL_AUSLEIHENBUTTON";
    public static final String SELECTPANEL_INFOLABEL = "SELECTPANEL_INFOLABEL";
    public static final String SELECTPANEL_DATELABLE = "SELECTPANEL_DATELABLE";
    public static final String SELECTPANEL_AUSGELIEHEN = "SELECTPANEL_AUSGELIEHEN";
    public static final String SELECTPANEL_VORHANDEN = "SELECTPANEL_VORHANDEN";
    public static final String SELECTPANEL_STATUS = "SELECTPANEL_STATUS";
    public static final String SELECTPANEL_STATUS_AUSGELIEHEN = "SELECTPANEL_STATUS_AUSGELIEHEN";
    public static final String SELECTPANEL_STATUS_GESPEICHERT = "SELECTPANEL_STATUS_GESPEICHERT";

    //SuchePanel
    public static final String SUCHEPANEL_KATEGORIELABLE = "SUCHEPANEL_KATEGORIELABLE";
    public static final String SUCHEPANEL_GENRELABLE = "SUCHEPANEL_GENRELABLE";
    public static final String SUCHEPANEL_SELECTBUTTON = "SUCHEPANEL_SELECTBUTTON";
}
